### ISSUE TITLE
server crashed

### ISSUE THREAD

**Issue by dreamaximum** [Minecraft-LightLand/L2Complements#2]
```
Description: Ticking entity

java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:764) ~[?:?] {}
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:786) ~[?:?] {}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:117) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:705) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:mixins.biomancy.json:MobEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2546) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obscure_api.mixins.json:LivingEntityMixin,pl:mixin:APP:l2complements.mixins.json:LivingEntityMixin,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:LivingEntityMixin,pl:mixin:APP:mixins.fishofthieves.json:entity.MixinLivingEntity,pl:mixin:APP:rottencreatures-common.mixins.json:common.LivingEntityMixin,pl:mixin:APP:unstructured.mixins.json:DamageMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.biomancy.json:LivingEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:504) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:mixins.biomancy.json:MobEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.monster.AbstractSkeleton.m_8107_(AbstractSkeleton.java:115) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2291) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obscure_api.mixins.json:LivingEntityMixin,pl:mixin:APP:l2complements.mixins.json:LivingEntityMixin,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:LivingEntityMixin,pl:mixin:APP:mixins.fishofthieves.json:entity.MixinLivingEntity,pl:mixin:APP:rottencreatures-common.mixins.json:common.LivingEntityMixin,pl:mixin:APP:unstructured.mixins.json:DamageMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.biomancy.json:LivingEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:316) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:mixins.biomancy.json:MobEntityAccessor,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.fishofthieves.json:level.MixinServerLevel,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.fishofthieves.json:level.MixinServerLevel,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.fishofthieves.json:level.MixinServerLevel,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:1589) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:764) ~[?:?] {}
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:786) ~[?:?] {}
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:117) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:705) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:mixins.biomancy.json:MobEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2546) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obscure_api.mixins.json:LivingEntityMixin,pl:mixin:APP:l2complements.mixins.json:LivingEntityMixin,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:LivingEntityMixin,pl:mixin:APP:mixins.fishofthieves.json:entity.MixinLivingEntity,pl:mixin:APP:rottencreatures-common.mixins.json:common.LivingEntityMixin,pl:mixin:APP:unstructured.mixins.json:DamageMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.biomancy.json:LivingEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:504) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:mixins.biomancy.json:MobEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.monster.AbstractSkeleton.m_8107_(AbstractSkeleton.java:115) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2291) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:obscure_api.mixins.json:LivingEntityMixin,pl:mixin:APP:l2complements.mixins.json:LivingEntityMixin,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:LivingEntityMixin,pl:mixin:APP:mixins.fishofthieves.json:entity.MixinLivingEntity,pl:mixin:APP:rottencreatures-common.mixins.json:common.LivingEntityMixin,pl:mixin:APP:unstructured.mixins.json:DamageMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:charmofundying.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.biomancy.json:LivingEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:316) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betteranimalsplus.mixins.json:MobAccessor,pl:mixin:APP:mixins.biomancy.json:MobEntityAccessor,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.fishofthieves.json:level.MixinServerLevel,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.fishofthieves.json:level.MixinServerLevel,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.fishofthieves.json:level.MixinServerLevel,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:A}
-- Entity being ticked --
Details:
	Entity Type: minecraft:wither_skeleton (net.minecraft.world.entity.monster.WitherSkeleton)
	Entity ID: 18142
	Entity Name: Wither Skeleton
	Entity's Exact location: 25.64, 36.00, 22.35
	Entity's Block location: World: (25,36,22), Section: (at 9,4,6 in 1,2,1; chunk contains blocks 16,0,16 to 31,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.11, 0.36, 0.30
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:457) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.fishofthieves.json:level.MixinServerLevel,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.fishofthieves.json:level.MixinServerLevel,pl:mixin:APP:rottencreatures-common.mixins.json:common.ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:1589) [?:?] {}


-- Affected level --
Details:
	All players: 2 total; [ServerPlayer['block_revolution'/386, l='ServerLevel[新的世界]', x=24.50, y=61.00, z=24.50], ServerPlayer['MojangcraftAB'/2669, l='ServerLevel[新的世界]', x=25.41, y=35.00, z=21.44]]
	Chunk stats: 2809
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (-2,59,-140), Section: (at 14,11,4 in -1,3,-9; chunk contains blocks -16,0,-144 to -1,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 12074024 game time, 12468348 day time
	Level name: 新的世界
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 35979 (now: false), thunder time: 90050 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:1589) [?:?] {}
```

**Comment by lcy0x1** [comment]
This is probably caused by some other mods. Please provide the full mod list
