### ISSUE TITLE
已知是L2 Complements, Tetra, Placebo 引发的问题,在整合包内复现是使用神化boss掉落的武器看向tetra的工作台

### ISSUE THREAD

**Issue by axlmly** [Minecraft-LightLand/L2Complements#4]
--- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-05-05 21:26:15
Description: Unexpected error

java.lang.LinkageError: loader constraint violation: loader 'MC-BOOTSTRAP' @4ae3c1cd wants to load interface org.apache.logging.log4j.util.MessageSupplier. (org.apache.logging.log4j.util.MessageSupplier is in module org.apache.logging.log4j@2.17.0 of loader 'MC-BOOTSTRAP' @4ae3c1cd, parent loader 'bootstrap')
	at net.minecraftforge.eventbus.EventBus.handleException(EventBus.java:329) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:320) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onDrawHighlight(ForgeHooksClient.java:261) ~[forge-1.19.2-43.2.8-universal.jar%23172!/:?] {re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1325) ~[client-1.19.2-20220805.130853-srg.jar%23167!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23167!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23167!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23167!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23167!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23167!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23167!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.8.jar%23150!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) [JavaWrapper.jar:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) [JavaWrapper.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.eventbus.EventBus.handleException(EventBus.java:329) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:320) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onDrawHighlight(ForgeHooksClient.java:261) ~[forge-1.19.2-43.2.8-universal.jar%23172!/:?] {re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1325) ~[client-1.19.2-20220805.130853-srg.jar%23167!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23167!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['steve'/174, l='ClientLevel', x=13.04, y=94.00, z=-5.40]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,86,0), Section: (at 0,6,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 6205 game time, 6205 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:450) ~[client-1.19.2-20220805.130853-srg.jar%23167!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2280) ~[client-1.19.2-20220805.130853-srg.jar%23167!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:722) ~[client-1.19.2-20220805.130853-srg.jar%23167!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23167!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23167!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.8.jar%23150!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) [JavaWrapper.jar:?] {}
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) [JavaWrapper.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, Minecraft-Mod-Language-Modpack-Converted-9.zip

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 19.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 812139232 bytes (774 MiB) / 2109734912 bytes (2012 MiB) up to 6337593344 bytes (6044 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x24dd
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3168
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 46891.87
	Virtual memory used (MB): 20712.38
	Swap memory total (MB): 30672.56
	Swap memory used (MB): 1413.39
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx6041m
	Launched Version: 1.19.2-Forge_43.2.8
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.68, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: file/Minecraft-Mod-Language-Modpack-Converted-9.zip
	Current Language: 简体中文 (中国大陆)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['steve'/174, l='ServerLevel[新的世界]', x=13.04, y=94.00, z=-5.40]]
	Data Packs: vanilla, mod:maxhealthfix (incompatible), mod:apotheosis (incompatible), mod:attributefix (incompatible), mod:forge, mod:tetra (incompatible), mod:placebo (incompatible), mod:mutil (incompatible), mod:mixinextras (incompatible), mod:l2library (incompatible), mod:l2complements (incompatible)
	World Generation: Experimental
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.8.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.8.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.8.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.8.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.8.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		tetra-1.19.2-5.2.1.jar                            |Tetra                         |tetra                         |5.2.1               |DONE      |Manifest: NOSIGNATURE
		[属性修复] AttributeFix-Forge-1.19.2-17.2.6.jar       |AttributeFix                  |attributefix                  |17.2.6              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		MaxHealthFix-Forge-1.19.2-8.0.1.jar               |MaxHealthFix                  |maxhealthfix                  |8.0.1               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		mixinextras-forge-0.2.0-beta.6.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.6        |DONE      |Manifest: NOSIGNATURE
		l2library-1.9.4.jar                               |L2 Library                    |l2library                     |1.9.4               |DONE      |Manifest: NOSIGNATURE
		[莱特兰-扩充] l2complements-1.3.0.jar                  |L2 Complements                |l2complements                 |1.3.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.8-universal.jar                 |Forge                         |forge                         |43.2.8              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		mutil-1.19.2-5.1.0.jar                            |mutil                         |mutil                         |5.1.0               |DONE      |Manifest: NOSIGNATURE
		[神化] Apotheosis-1.19.2-6.1.5.jar                  |Apotheosis                    |apotheosis                    |6.1.5               |DONE      |Manifest: NOSIGNATURE
		Placebo-1.19.2-7.1.8.jar                          |Placebo                       |placebo                       |7.1.8               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: bf20323f-4b79-4d8e-be27-92d76c604df5
	FML: 43.2
	Forge: net.minecraftforge:43.2.8
![image](https://user-images.githubusercontent.com/41771421/236603332-30855ae8-319e-4fa5-a7d7-a838205db89e.png)

**Comment by lcy0x1** [comment]
Java无法加载某个类，看起来不像是mod的问题。我测试一下，看看能不能复现

**Comment by lcy0x1** [comment]
你试试把java19改成java17

**Comment by lcy0x1** [comment]
复现成功，我看看

**Comment by lcy0x1** [comment]
具体错误：
```

	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.modifyReturnValue$zze000$l2complements_getMaxDamage_durabilityEnchantment(ItemStack.java:1249)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.getMaxDamage(ItemStack.java:349)
	at TRANSFORMER/tetra@5.2.1/se.mickelus.tetra.items.modular.IModularItem.isBroken(IModularItem.java:454)
	at TRANSFORMER/tetra@5.2.1/se.mickelus.tetra.items.modular.ItemModularHandheld.getToolActions(ItemModularHandheld.java:848)
	at TRANSFORMER/tetra@5.2.1/se.mickelus.tetra.items.modular.ItemModularHandheld.canPerformAction(ItemModularHandheld.java:856)
	at TRANSFORMER/forge@43.2.0/net.minecraftforge.common.extensions.IForgeItemStack.canPerformAction(IForgeItemStack.java:117)
	at TRANSFORMER/apotheosis@6.1.5/shadows.apotheosis.adventure.loot.LootCategory.lambda$static$4(LootCategory.java:49)
	at TRANSFORMER/apotheosis@6.1.5/shadows.apotheosis.adventure.loot.LootCategory.isValid(LootCategory.java:92)
	at TRANSFORMER/apotheosis@6.1.5/shadows.apotheosis.adventure.loot.LootCategory.forItem(LootCategory.java:181)
	at TRANSFORMER/apotheosis@6.1.5/shadows.apotheosis.adventure.affix.effect.PotionAffix.canApplyTo(PotionAffix.java:102)
	at TRANSFORMER/apotheosis@6.1.5/shadows.apotheosis.adventure.affix.AffixHelper.getAffixes(AffixHelper.java:77)
	at TRANSFORMER/apotheosis@6.1.5/shadows.apotheosis.adventure.affix.AffixHelper.streamAffixes(AffixHelper.java:86)
	at TRANSFORMER/apotheosis@6.1.5/shadows.apotheosis.adventure.AdventureEvents.enchLevels(AdventureEvents.java:412)
	at TRANSFORMER/apotheosis@6.1.5/shadows.apotheosis.adventure.__AdventureEvents_enchLevels_GetEnchantmentLevelEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/placebo@7.1.8/shadows.placebo.events.PlaceboEventFactory.getEnchantmentLevelSpecific(PlaceboEventFactory.java:31)
	at TRANSFORMER/forge@43.2.0/net.minecraftforge.common.extensions.IForgeItemStack.getEnchantmentLevel(IForgeItemStack.java:178)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.modifyReturnValue$zze000$l2complements_getMaxDamage_durabilityEnchantment(ItemStack.java:1249)
```

**Comment by lcy0x1** [comment]
v1.3.1修好了

**Comment by axlmly** [comment]
> v1.3.1修好了

哦你好快我还没测试呢

**Comment by lcy0x1** [comment]
上传通过了。Apotheosis也修复了这个问题了
