### ISSUE TITLE
与ItemPhysic同时使用导致游戏无法启动

### ISSUE THREAD

**Issue by Dr-WeiAL** [Minecraft-LightLand/L2Complements#6]
已测试
L2Complements 1.3.0版本没有这个问题
最新的1.4.5有这个问题
```
[15Jun2023 11:46:13.767] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, WeiAL, --version, 1.19.2, --gameDir, E:/PrismLauncher/instances/1.19.2Forge 测试/.minecraft, --assetsDir, C:/Users/WeiAL/AppData/Roaming/PrismLauncher/assets, --assetIndex, 1.19, --uuid, 5ba80d703b56445b86c8f861e352ddf0, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.11, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, --width, 854, --height, 480]
[15Jun2023 11:46:13.775] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.1 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[15Jun2023 11:46:14.056] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/WeiAL/AppData/Roaming/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23146!/ Service=ModLauncher Env=CLIENT
[15Jun2023 11:46:14.437] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\WeiAL\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.11\fmlcore-1.19.2-43.2.11.jar is missing mods.toml file
[15Jun2023 11:46:14.447] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\WeiAL\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.11\javafmllanguage-1.19.2-43.2.11.jar is missing mods.toml file
[15Jun2023 11:46:14.457] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\WeiAL\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.11\lowcodelanguage-1.19.2-43.2.11.jar is missing mods.toml file
[15Jun2023 11:46:14.466] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\WeiAL\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.11\mclanguage-1.19.2-43.2.11.jar is missing mods.toml file
[15Jun2023 11:46:14.599] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 2 dependencies adding them to mods collection
[15Jun2023 11:46:15.851] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[15Jun2023 11:46:15.882] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19.2, --gameDir, E:\PrismLauncher\instances\1.19.2Forge 测试\.minecraft, --assetsDir, C:\Users\WeiAL\AppData\Roaming\PrismLauncher\assets, --uuid, 5ba80d703b56445b86c8f861e352ddf0, --username, WeiAL, --assetIndex, 1.19, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480]
[15Jun2023 11:46:16.005] [main/WARN] [mixin/]: Reference map 'l2artifacts.refmap.json' for l2artifacts.mixins.json could not be read. If this is a development environment you can ignore this message
[15Jun2023 11:46:18.046] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed l2complements.mixins.json:ItemEntityMixin -> net.minecraft.world.entity.item.ItemEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/world/entity/item/ItemEntity::l2complments_hurt_itemBurnt with priority 1000 cannot inject into net/minecraft/world/entity/item/ItemEntity::m_6469_(Lnet/minecraft/world/damagesource/DamageSource;F)Z merged by team.creative.itemphysic.mixin.ItemEntityMixin with priority 1000 [PREINJECT Applicator Phase -> l2complements.mixins.json:ItemEntityMixin -> Prepare Injections ->  -> handler$zzl000$l2complments_hurt_itemBurnt(Lnet/minecraft/world/damagesource/DamageSource;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/world/entity/item/ItemEntity::l2complments_hurt_itemBurnt with priority 1000 cannot inject into net/minecraft/world/entity/item/ItemEntity::m_6469_(Lnet/minecraft/world/damagesource/DamageSource;F)Z merged by team.creative.itemphysic.mixin.ItemEntityMixin with priority 1000 [PREINJECT Applicator Phase -> l2complements.mixins.json:ItemEntityMixin -> Prepare Injections ->  -> handler$zzl000$l2complments_hurt_itemBurnt(Lnet/minecraft/world/damagesource/DamageSource;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraftforge.registries.GameData.init(GameData.java:108) ~[forge-1.19.2-43.2.11-universal.jar%23176!/:?]
	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:93) ~[forge-1.19.2-43.2.11-universal.jar%23176!/:?]
	at net.minecraft.core.Registry.forge(Registry.java:435) ~[client-1.19.2-20220805.130853-srg.jar%23171!/:?]
	at net.minecraft.core.Registry.forge(Registry.java:419) ~[client-1.19.2-20220805.130853-srg.jar%23171!/:?]
	at net.minecraft.core.Registry.<clinit>(Registry.java:186) ~[client-1.19.2-20220805.130853-srg.jar%23171!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23171!/:?]
	at net.minecraft.client.main.Main.lambda$run$0(Main.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23171!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

```

**Comment by lcy0x1** [comment]
更新ItemPhysics。这个问题是他们那边的问题，并且他们已经解决了
